# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('inicio', models.DateField(verbose_name='inicio do curso')),
                ('fim', models.DateField(verbose_name='fim do curso')),
                ('carga_horaria', models.IntegerField(verbose_name='carga horaria')),
                ('coordenador', models.CharField(max_length=80, verbose_name='coordenador')),
                ('ministrante', models.CharField(max_length=80, verbose_name='ministrante')),
                ('cidade', models.CharField(max_length=30, verbose_name='cidade')),
                ('modelo', models.FileField(blank=True, null=True, upload_to=None, verbose_name='modelo de certificados')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='cpf')),
                ('telefone', models.CharField(max_length=11, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('matricula', models.CharField(blank=True, max_length=11, null=True, verbose_name='matricula')),
            ],
        ),
        migrations.AddField(
            model_name='certificado',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='certificados.Curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='certificados.Participante', verbose_name='Participante'),
        ),
    ]
